export const FETCH_TOP_30_COIN_LIST= 'FETCH_TOP_30_COIN_LIST';
export const FETCH_TOP_30_COIN_LIST_SUCCESS = 'FETCH_TOP_30_COIN_LIST_SUCCESS';
export const FFETCH_TOP_30_COIN_LIST_FAILED = 'FFETCH_TOP_30_COIN_LIST_FAILED';

export const ADD_COIN_BY_PORTFILO_ID = 'ADD_COIN_BY_PORTFILO_ID';
export const ADD_COIN_BY_PORTFILO_ID_SUCCESS = 'ADD_COIN_BY_PORTFILO_ID_SUCCESS';
export const ADD_COIN_BY_PORTFILO_ID_FAILED = 'ADD_COIN_BY_PORTFILO_ID_FAILED';

export const FETCH_COIN_BY_PORTFILO_ID = 'FETCH_COIN_BY_PORTFILO_ID';
export const FETCH_COIN_BY_PORTFILO_ID_SUCCESS = 'FETCH_COIN_BY_PORTFILO_ID_SUCCESS';
export const FETCH_COIN_BY_PORTFILO_ID_FAILED = 'FETCH_COIN_BY_PORTFILO_ID_FAILED';

export const FETCH_COIN_BY_NAME = 'FETCH_COIN_BY_NAME';
export const FETCH_COIN_BY_NAME_SUCCESS = 'FETCH_COIN_BY_NAME_SUCCESS';
export const FETCH_COIN_BY_NAME_FAILED = 'FETCH_COIN_BY_NAME_FAILED';

export const FETCH_COIN_FULL_DATA = 'FETCH_COIN_FULL_DATA';
export const FETCH_COIN_FULL_DATA_SUCCESS = 'FETCH_COIN_FULL_DATA_SUCCESS';
export const FETCH_COIN_FULL_DATA_FAILED = 'FETCH_COIN_FULL_DATA_FAILED';

export const DELETE_COIN_BY_PORTFILO_ID = 'DELETE_COIN_BY_PORTFILO_ID';
export const DELETE_COIN_BY_PORTFILO_ID_SUCCESS = 'DELETE_COIN_BY_PORTFILO_ID_SUCCESS';
export const DELETE_COIN_BY_PORTFILO_ID_FAILED = 'DELETE_COIN_BY_PORTFILO_ID_FAILED';