export const ADD_PORTFOLIO= 'ADD_PORTFOLIO';
export const ADD_PORTFOLIO_SUCCESS = 'ADD_PORTFOLIO_SUCCESS';
export const ADD_PORTFOLIO_FAILED = 'ADD_PORTFOLIO_FAILED';

export const FETCH_PORTFOLIOS_LIST= 'FETCH_PORTFOLIOS_LIST';
export const FETCH_PORTFOLIOS_LIST_SUCCESS = 'FETCH_PORTFOLIOS_LIST_SUCCESS';
export const FETCH_PORTFOLIOS_LIST_FAILED = 'FETCH_PORTFOLIOS_LIST_FAILED';

export const FETCH_HISTORY_PORTFOLIOS_90_DAYS_LIST= 'FETCH_HISTORY_PORTFOLIOS_90_DAYS_LIST';
export const FETCH_HISTORY_PORTFOLIOS_90_DAYS_LIST_SUCCESS = 'FETCH_HISTORY_PORTFOLIOS_90_DAYS_LIST_SUCCESS';
export const FETCH_HISTORY_PORTFOLIOS_90_DAYS_LIST_FAILED = 'FETCH_HISTORY_PORTFOLIOS_90_DAYS_LIST_FAILED';